{{- if not .Values.env.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "github-mcp-server.fullname" . }}
  labels:
    {{- include "github-mcp-server.labels" . | nindent 4 }}
type: Opaque
data:
  GITHUB_PERSONAL_ACCESS_TOKEN: {{ .Values.env.personalAccessToken | b64enc | quote }}
{{- end }}
